### ISSUE TITLE
The use of pre-trained models for generating commit messages

### ISSUE THREAD

**Issue by Yuuoniy** [JetBrains-Research/commit_message_generation#9]
Dear Authors,

Thank you for your excellent work! I am very interested in it and am now attempting to apply it to specific commits. I have questions regarding the use of [pre-trained models](https://huggingface.co/JetBrains-Research/cmg-codet5-without-history/tree/main) for Commit Message Generation (CMG).

Could you provide a simple example or guide on how to use these pre-trained models for a given commit diff? Or could you please explain the preprocessing steps necessary for this? It seems that models like CodeT5, RACE, and CodeReviewer require different preprocessing. 

Your guidance would be greatly beneficial. Thank you in advance for your help.

**Comment by saridormi** [comment]
Hello! Thank you very much for the kind words :heart: and sorry for the long answer.

We indeed use slightly different diffs preprocessing for all three models. For CodeT5, we simply concatenate diffs for all the modified files into a single string, while for RACE and CodeReviewer we also follow additional preprocessing steps from the corresponding papers. We have all the code for preprocessing located under [`src/data_utils/preprocessors`](https://github.com/JetBrains-Research/commit_message_generation/tree/main/src/data_utils/preprocessors) folder. 

Thank you for highlighting this issue, I agree that it's non-intuitive and would be way more convenient if we provide a simple guide for each model, e.g., on corresponding :hugs: HuggingFace pages. I'll try to get to it soon! 

In the meantime, if you use our pipeline for evaluation, a preprocessor is selected based on a `preprocessor_configuration` entry in a [model's config](https://github.com/JetBrains-Research/commit_message_generation/blob/main/conf/model/base_configs.py). Otherwise, you can reuse our preprocessors:
* [`default_preprocessor`](https://github.com/JetBrains-Research/commit_message_generation/blob/main/src/data_utils/preprocessors/default_preprocessor.py) for CodeT5
* [`race_preprocessor`](https://github.com/JetBrains-Research/commit_message_generation/blob/main/src/data_utils/preprocessors/race_preprocessor.py) for RACE
* [`codereviewer_preprocessor`](https://github.com/JetBrains-Research/commit_message_generation/blob/main/src/data_utils/preprocessors/codereviewer_preprocessor.py) for CodeReviewer

You would probably be interested in [`_preprocess_diff`](https://github.com/JetBrains-Research/commit_message_generation/blob/main/src/data_utils/preprocessors/default_preprocessor.py#L7), [`_preprocess_mods`](https://github.com/JetBrains-Research/commit_message_generation/blob/main/src/data_utils/preprocessors/default_preprocessor.py#L11) and [`_tokenize_diffs`](https://github.com/JetBrains-Research/commit_message_generation/blob/main/src/data_utils/preprocessors/base_preprocessor.py#L44) methods. 

I hope that answers your question, but feel free to let me know if I can be of help!

**Comment by Yuuoniy** [comment]
Hi, saridormi

Thank you so much for your help, now I've basically sorted out how to do.
